# Generated by Django 4.2.5 on 2023-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rooms',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
