# Generated by Django 4.2.5 on 2023-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rooms_city_rooms_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
