# Generated by Django 4.2.5 on 2023-10-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rooms_garagge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='garagge',
            new_name='garage',
        ),
    ]
