# Generated by Django 4.1.11 on 2023-10-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_garagge_rooms_garage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(default='', upload_to='rooms/images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(default='', upload_to='rooms/images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(default='', upload_to='rooms/images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image5',
            field=models.ImageField(default='', upload_to='rooms/images/'),
        ),
    ]
