# Generated by Django 4.1.11 on 2023-10-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_image_rooms_image1_rooms_image2_rooms_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='image1',
            new_name='image',
        ),
    ]
