# Generated by Django 4.1.11 on 2023-10-18 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_rename_image1_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
