# Generated by Django 4.1.11 on 2023-10-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_rooms_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='rooms/images/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(blank=True, default='', upload_to='rooms/images/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='rooms/images/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='rooms/images/'),
        ),
    ]
