# Generated by Django 4.1.11 on 2023-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_rooms_image2_alter_rooms_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='renter',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
