# Generated by Django 4.2.5 on 2023-11-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
