# Generated by Django 4.1.11 on 2023-11-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_profile'),
        ('rooms', '0016_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Reseña',
        ),
    ]
