# Generated by Django 4.1.11 on 2023-11-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reseña'),
        ('rooms', '0017_rename_comentario_reseña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Comentario',
        ),
    ]
